# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_charges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charges',
            new_name='Charge',
        ),
    ]
