# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20160816_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='charge',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.KindCharge'),
        ),
    ]
