# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0005_auto_20160818_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Almancén'),
            preserve_default=False,
        ),
    ]
