# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='shipment',
            new_name='store',
        ),
    ]
