# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_auto_20160904_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='saldo',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
