# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_shipment_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='saldo',
            field=models.BigIntegerField(default=0),
        ),
    ]
