# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_auto_20160907_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='saldo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
