# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
