# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_shipment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
