# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_permission',
            field=models.BooleanField(default=False),
        ),
    ]
