# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_has_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.CharField(blank=True, choices=[('socio', 'Socio'), ('almacen', 'Almancén')], max_length=15, null=True),
        ),
    ]
