# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
