# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160825_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=False, upload_to='users'),
            preserve_default=False,
        ),
    ]
