# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160924_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('Dólares', 'Dólares'), ('Pesos mexicanos', 'Pesos mexicanos')], max_length=15),
        ),
    ]
