# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160924_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(choices=[('Dólares', 'Dólares'), ('Pesos mexicanos', 'Pesos mexicanos')], default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('mxn', 'MXN')], max_length=15),
        ),
    ]
