# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='notification',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='users.Notification'),
            preserve_default=False,
        ),
    ]
