# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20160816_0525'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.Charge'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment'),
        ),
    ]
