# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20160818_0406'),
        ('stores', '0002_auto_20160818_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='kind_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.KindCharge'),
        ),
    ]
