# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20160821_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
