# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_movement_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movement',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
