# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0006_auto_20160825_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='store',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
