# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_movement_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='image',
            field=models.ImageField(default=False, upload_to='movements'),
            preserve_default=False,
        ),
    ]
