# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_movement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindmovement',
            name='store',
            field=models.BooleanField(default=False),
        ),
    ]
