# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_auto_20160908_0001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20160924_1119'),
        ('stores', '0009_kindmovement_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movements')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Account')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.Charge')),
                ('kind_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.KindCharge')),
                ('kind_mov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.KindMovement')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.Shipment')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
