# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_abono'),
        ('stores', '0011_sociomovement_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociomovement',
            name='kind_abono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.Abono'),
        ),
        migrations.AlterField(
            model_name='sociomovement',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
    ]
