# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_auto_20160924_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociomovement',
            name='type_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
