# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_sociomovement_type_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociomovement',
            name='type_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
