# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_auto_20161002_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='waiting',
            field=models.BooleanField(default=True),
        ),
    ]
