# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_movement_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociomovement',
            name='waiting',
            field=models.BooleanField(default=True),
        ),
    ]
