# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_sociomovement_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociomovement',
            name='precio_costo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
