# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_sociomovement_precio_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociomovement',
            name='precio_costo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
